name: notify
on: 
  workflow_dispatch:
  schedule:
    - cron: '5/5 * * * *'

jobs:
  notify_friends:
    runs-on: alpine
    steps:
      - name: Call notification service
        run: curl https://acolytec3-floor-atcher.deno.dev